version: "3.7"

services:
    start:
        image: node:latest
        ports:
            - 8080:8080
        volumes:
            - ../:/app
        working_dir: /app
        command: npm run start -- --host=0.0.0.0
    build:
        build:
            context: .
            dockerfile: build.Dockerfile
        image: kevinpainchaud/portfolio-v6-build:latest
        volumes:
            - ../:/app
        working_dir: /app
        command: npm run build
    serve:
        image: node:latest
        ports:
            - 5000:5000
        volumes:
            - ../:/app
        working_dir: /app
        command: npm run serve
    fetch-linkedin:
        build:
            context: .
            dockerfile: fetch-linkedin.Dockerfile
        image: kevinpainchaud/portfolio-v6-fetch-linkedin:latest
        volumes:
            - ../:/app
        working_dir: /app
        command: npm run fetch-linkedin
