version: "3.7"

services:
    build:
        image: node:latest
        volumes:
            - ../:/app
            - /app/node_modules/puppeteer
        working_dir: /app
        command: npm run build
    start:
        image: node:latest
        ports:
            - 3000:3000
        volumes:
            - ../:/app
        working_dir: /app
        command: npm run start
    fetch-linkedin:
        build:
            context: .
            dockerfile: images/fetch-linkedin.Dockerfile
        image: kevinpainchaud/portfolio-v6-fetch-linkedin:latest
        volumes:
            - ../:/app
        working_dir: /app
        command: python3 ./tools/fetch-linkedin.py
